# Ingress allows external users and outside client applications access to HTTP services.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-project-ingress
  namespace: devops-project-namespace
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/ssl-passthrough: "true" # For AgroCD
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-project-service
                port:
                  number: 8080


# NAME                    TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
#ingress-nginx-controller LoadBalancer   10.105.3.47  localhost     80:30166/TCP,443:30975/TCP   55m

#    - host: devops-project.com
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: devops-project-service
#                port:
#                  number: 8080
